name: Deploy to Ubuntu

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.220.155.83 << 'EOF'
            cd /var/www/your-app
            git pull origin main
            sudo systemctl restart your-service
          EOF
