name: My First Workflow

on: [push]  # Runs on every code push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v4
  - name: List project files  # 👈 New step
    run: ls -la
  - name: Count Python files  # 👈 Another step
    run: find . -name "*.py" | wc -l
